export enum AccidentType {
  VEHICLE_COLLISION = 'VEHICLE_COLLISION',
  FALLING_POLE = 'FALLING_POLE',
  VANDALISM = 'VANDALISM',
  NATURAL_DISASTER = 'NATURAL_DISASTER',
  ELECTRICAL_FAULT = 'ELECTRICAL_FAULT',
  OTHER = 'OTHER',
}

export enum DamageLevel {
  MINOR = 'MINOR',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  TOTAL_LOSS = 'TOTAL_LOSS',
}

export enum AccidentStatus {
  REPORTED = 'REPORTED',
  INSPECTED = 'INSPECTED',
  SUPERVISOR_REVIEW = 'SUPERVISOR_REVIEW',
  FINANCE_REVIEW = 'FINANCE_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  UNDER_REPAIR = 'UNDER_REPAIR',
  COMPLETED = 'COMPLETED',
}

export enum ClaimStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PAID = 'PAID',
}

export enum ApprovalStage {
  SUPERVISOR_REVIEW = 'SUPERVISOR_REVIEW',
  FINANCE_REVIEW = 'FINANCE_REVIEW',
}

export enum ApprovalAction {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}

export enum DamagedComponent {
  POLE = 'POLE',
  LUMINAIRE = 'LUMINAIRE',
  ARM_BRACKET = 'ARM_BRACKET',
  FOUNDATION = 'FOUNDATION',
  CABLE = 'CABLE',
}

// Cost estimation tables (predefined rates)
export const COST_ESTIMATION_TABLES = {
  POLE_TYPES: {
    STANDARD: { MINOR: 500, MODERATE: 1500, SEVERE: 3000, TOTAL_LOSS: 5000 },
    DECORATIVE: { MINOR: 800, MODERATE: 2400, SEVERE: 4800, TOTAL_LOSS: 8000 },
    HIGH_MAST: { MINOR: 1500, MODERATE: 4500, SEVERE: 9000, TOTAL_LOSS: 15000 },
  },
  COMPONENTS: {
    LUMINAIRE: { MINOR: 200, MODERATE: 400, SEVERE: 600, TOTAL_LOSS: 800 },
    ARM_BRACKET: { MINOR: 150, MODERATE: 300, SEVERE: 500, TOTAL_LOSS: 700 },
    FOUNDATION: { MINOR: 300, MODERATE: 600, SEVERE: 1000, TOTAL_LOSS: 2000 },
    CABLE: { MINOR: 100, MODERATE: 250, SEVERE: 500, TOTAL_LOSS: 800 },
  },
  FIXED_COSTS: {
    LABOR: 300,
    TRANSPORT_TRAFFIC_CONTROL: 200,
  },
};
